config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
  get "/show_list" => "users#show_list"
  get "/login" => "users#login"
  get  "/successful" => "users#successful"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    validates :password, presence: true, length:{minimum:2}
    # FORM =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
    validates :email , presence: true, format:{with: /\A([^@\s]+)@(([a-zA-Z0-9]+\.)+[a-zA-Z.]{2,5})\z/}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
require 'digest'

class UsersController < ApplicationController
    include UsersHelper
      before_action :set_user, only: [ :show, :edit, :destroy, :update]
    def new 
        @users = User.new
    end

    def index
    end
    
    def show   
    end

    def show_list
    end

    def create
        if encode.save
            respond_to do |format|
                format.html { render :show}
            end
        else
            render :index
        end
    end    
    def successful
    end

    def login  
        password = Digest::MD5.hexdigest(params[:password])
        k =User.where(email: "#{params[:email]}", password: "#{password}")
        if k.size == 0
             render :index
        else
            redirect_to :controller => "users", :action => "successful"
            
        end
    end 

    def edit
    end
    
    def destroy
        if @user.destroy
            redirect_to :action => 'show_list' 
        end
    end
    
    private
    def set_user
        @user = User.find(params[:id])
    end

    def users_params
        params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def encode
        @user = User.new(users_params) 
        @user.password = Digest::MD5.hexdigest(@user.password)
        return @user
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appdemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h1 class="title">=====SIG UP =======</h1>
  </div>

 <div class = "errors">
    <% if @user.nil? %>
      
    <%else%>
      <% if @user.errors.any? %>
        <h1>Errors</h1>
        <ul>
        <% @user.errors.full_messages.each do |m|%> 
            <li> <%= m %> </li>
        <% end %>
        </ul>
      <% end %>
    <% end %>
  </div>

  <div class="row">
    <div >
      <%= form_for :user, turbo: false do |f| %>

        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: "from-control", placeholder: "aaa@gamil.com" %>
        </div></br>
        
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: "from-control", placeholder: "password" %>
        </div>

        <div class="form-group">
          <%= f.submit "Sig up" %>
        </div></br>
      <% end %>
      <h1 class="title">=====LOG IN =======</h1>
      <%= form_with  url: login_path, method: :get do |form| %>
         <div class="form-group">
          <%= form.label :email %>
          <%= form.text_field :email, class: "from-control", placeholder: "aaa@gamil.com" %>
        </div></br>
        
        <div class="form-group">
          <%= form.label :password %>
          <%= form.password_field :password, class: "from-control", placeholder: "password" %>
        </div>

        <%= form.submit "login" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1>Account</h1>
 <p>email: <%= @user.email %></p>
 <p>password: <%= @user.password %></p>
<%= link_to "show list users", show_list_path %>
<%= link_to "Destroy this user", @user, method: :delete %>

app/views/users/show_list.html.erb
<h1>List users</h1>
<% @users = User.all%>
<% @users.each do |i|%>
    <p>email: <%= i.email%></p>
    <p>email: <%= i.password%></p>
    <%= link_to "detail", user_path(i) %>
<% end %>

app/views/users/successful.html.erb
<h1>LOG IN SUCCESSFUL</h1>